name: File Parser 2025E Lambda Deployment

on:
  workflow_dispatch:
    inputs:
      aws_access_key_id:
        description: "AWS Access Key ID"
        required: true
      aws_secret_access_key:
        description: "AWS Secret Access Key"
        required: true
      region:
        description: "AWS Region"
        required: true
      token:
        description: "Github Token"
        required: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CF_STACK_FILE_PARSER_2025E: ${{ vars.CF_STACK_FILE_PARSER_2025E }}
    steps:
      - name: Check out ASM_BaseStation repository
        uses: actions/checkout@main
        with:
          repository: weiwentan23/TestLambda
          token: ${{ github.event.inputs.token }}

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.x'

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli -y

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ github.event.inputs.aws_access_key_id }}
          aws-secret-access-key: ${{ github.event.inputs.aws_secret_access_key }}
          aws-region: ${{ github.event.inputs.region }}

      - name: "[File Parser 2025E] Deploy Lambda Function"
        run: |
          cd aws/lambda/file-parser-2025e && \
          dotnet restore && \
          dotnet build --configuration Release && \
          dotnet lambda package --configuration Release --output-package ./bin/Release/net7.0/package.zip && \
          sam build && \
          sam deploy \
            --stack-name ${CF_STACK_FILE_PARSER_2025E} \
            --s3-bucket "verisense-assets-${{ github.event.inputs.vts_id }}" \
            --s3-prefix "sam/${CF_STACK_FILE_PARSER_2025E}" \
            --region "${{ github.event.inputs.region }}" \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset \
            --no-confirm-changeset \