name: File Parser 2025E Lambda Deployment

on:
  workflow_dispatch:
    inputs:
      aws_access_key_id:
        description: "AWS Access Key ID"
        required: true
      aws_secret_access_key:
        description: "AWS Secret Access Key"
        required: true
      token:
        description: "Github Token"
        required: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CF_STACK_FILE_PARSER_2025E: ${{ vars.CF_STACK_FILE_PARSER_2025E }}
    steps:
      - name: Check out ASM_BaseStation repository
        uses: actions/checkout@main
        with:
          repository: weiwentan23/TestLambda
          token: ${{ github.event.inputs.token }}

      - name: List repository files and directories
        run: |
          echo "Listing all files and directories:"
          ls -R

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'

      - name: Install dotnet-lambda tool
        run: |
          dotnet tool install -g Amazon.Lambda.Tools
          export PATH="$PATH:/home/runner/.dotnet/tools"

      # - name: Restore .NET dependencies
      #   run: |
      #     cd TestLambdaFunction
      #     dotnet restore

      # - name: Build .NET project
      #   run: |
      #     cd TestLambdaFunction
      #     dotnet build --configuration Release

      # - name: Package Lambda function
      #   run: |
      #     cd TestLambdaFunction
      #     dotnet lambda package --configuration Release --output-package ./bin/Release/net6.0/package.zip

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli -y

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ github.event.inputs.aws_access_key_id }}
          aws-secret-access-key: ${{ github.event.inputs.aws_secret_access_key }}
          aws-region: us-east-2

      # - name: Deploy to Lambda
      #   working-directory: ./TestLambdaFunction
      #   run: dotnet lambda deploy-serverless

      - name: "[File Parser 2025E] Deploy Lambda Function"
        run: |
          cd TestLambdaFunction && \
          dotnet restore && \
          dotnet build --configuration Release && \
          dotnet lambda package --configuration Release --output-package ./bin/Release/net6.0/package.zip && \
          sam build && \
          sam deploy \
            --guided
            --stack-name lambda-function-test-deploy \
            --s3-bucket "verisense-assets-0148" \
            --s3-prefix "sam/lambda-function-test-deploy" \
            --region "us-east-2" \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset \
            --no-confirm-changeset \